#!/bin/bash
set -eu

# Resource Directories
export REPO_ROOT="git"
export BUILD_ROOT="build"
export CI_ROOT="git-ci"
export VERSION_FROM="version/number"

header() {
	echo
	echo "================================================================================"
	echo "$1"
	echo "--------------------------------------------------------------------------------"
	echo
}

bail() {
	echo >&2 "$*  Did you misconfigure Concourse?"
	exit 2
}
test -n "${PROJECT:-}"        || bail "PROJECT must be set to the name of this package."

test -f "${VERSION_FROM}"     || bail "Version file (${VERSION_FROM}) not found."
VERSION=$(cat "${VERSION_FROM}")
test -n "${VERSION}"          || bail "Version file (${VERSION_FROM}) was empty."

header "Building $PROJECT v$VERSION..."

cd "$REPO_ROOT"
go version; echo; echo
make clean release-all VERSION=$VERSION PROJECT=$PROJECT
cd release
tar -zcvf ../../$BUILD_ROOT/$PROJECT-$VERSION.tar.gz $PROJECT-$VERSION-*

echo
echo "================================================================================"
echo "SUCCESS!"
exit 0
