---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: registry.ops.scalecf.net/genesis-community/concourse-go
    tag: latest

inputs:
- name: version
- name: git
- name: git-ci

outputs:
- name: build

run:
  path: git-ci/ci/scripts/build
