jobs:
  - name: test
    public: true
    serial: true
    plan:
    - { get: git, trigger: true }
    - task: test
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: (( grab meta.image.name ))
            tag:        (( grab meta.image.tag ))
        inputs:
          - name: git
            path: (( concat "gopath/src/" meta.go.module ))
        run:
          path: (( concat "./gopath/src/" meta.go.module "/ci/scripts/test" ))
          args: []
        params:
          MODULE: (( grab meta.go.module ))
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:    '(( concat meta.slack.fail_url " " meta.pipeline ": test job failed" ))'

