jobs:
  - name: test-vault1.13
    public: true
    serial: false
    plan:
    - in_parallel: 
      steps: 
      - { get: github-vault-13, trigger: true }
      - { get: build, trigger: true }
      - { get: git }
      - { get: git-ci}
    - load_var: vault_version
      file_path: github-vault-13/tag
      format: trim
      reveal: true
    - task: test
      file: git-ci/ci/tasks/test.yml
      params:
        PROJECT: (( grab meta.go.project ))
        VAULT_VERSIONS: ((.:vault_version))
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:    '(( concat meta.slack.fail_url " " meta.pipeline ": test job failed" ))'

